sudo: false

services:
  - docker

cache:
  directories:
    - .autoconf
    - $HOME/.m2
    - "~/docker"

env:
  - TEST_TYPE=other
  - TEST_TYPE=unit
  # - TEST_TYPE=coverage

before_install:
  - if [[ -e ~/docker/image.tar ]]; then echo "Using docker cache" && docker load -i ~/docker/image.tar; fi

script:
  # Run different test types
  - scripts/test/test.sh
  - mkdir -p ~/docker; docker save jarjs:test > ~/docker/image.tar