sudo: false

services:
  - docker

before_install:
  - docker build -t jarjs:test .

script:
  # Compile ts files
  - docker run -t -v ./:usr/src/app jarjs:test
  # Run tslint on all .ts files (except those in node_modules, typings)
  - docker run -t -v ./:usr/src/app jarjs:test find -name "*.ts" -not \( -path "./node_modules/*" -o -path "./typings/*" \) -prune
  # Run default command
  - docker run -t -v ./:usr/src/app jarjs:test
